# Generated by Django 2.0 on 2018-04-27 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('movid', models.CharField(default=0, max_length=100, primary_key=True, serialize=False)),
                ('runtime', models.CharField(max_length=6)),
                ('genres', models.CharField(max_length=120)),
                ('releaseDate', models.DateField(null=True)),
                ('rating', models.CharField(max_length=6)),
                ('poster', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=8)),
                ('showid', models.CharField(max_length=100)),
                ('ticketingUrl', models.CharField(max_length=400)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theaters.Movie')),
            ],
            options={
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('addressOne', models.CharField(max_length=200)),
                ('addressTwo', models.CharField(max_length=200, null=True)),
                ('agePolicy', models.CharField(max_length=400, null=True)),
                ('city', models.CharField(max_length=100)),
                ('theaterName', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=5)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lat', models.CharField(blank=True, max_length=10, null=True)),
                ('lng', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='theaters',
            field=models.ManyToManyField(to='theaters.Theater'),
        ),
    ]
